Lesson_3_1
betymesfin/React_Todo pull request #11
Opened 2024-09-12 17:36 UTC by betymesfin

2024-09-18 14:15 UTC, codiini requested changes

2024-09-18 14:15 UTC, codiini commented on src/index.css
Convert this to a modular stylesheet and use it for styling.

2024-09-18 14:16 UTC, codiini commented
Great job with the custom font and background image, but convert the index.css file to use modules and you're all good.

2024-09-19 16:48 UTC, betymesfin commented on src/index.css
done

2024-10-01 00:01 UTC, codiini commented
> Great job with the custom font and background image, but convert the index.css file to use modules and you're all good.

Hey Beth, sorry about the back and forth, but please change it to a regular CSS stylesheet. I sent you a message on Slack

2024-10-03 18:49 UTC, merged